apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketcap-deployment
spec:
  selector:
    matchLabels:
      app: marketcap
  template:
    metadata:
      labels:
        app: marketcap
    spec:
      containers:
      - name: marketcap
        image: dizzycoder1112/marketcap
        resources:
          limits:
            memory: "4Gi"
            cpu: "1"
        ports:
        - containerPort: 50054
